FROM maven:3.6.1-jdk-8-alpine

WORKDIR /jwtapp

#Copy all sources
COPY ./spring-jwt .

#Build ( because you want to execute tests after the spring boot application is started you should disable test during build phase )
RUN mvn install -DskipTests

#Start container
COPY commands.sh /scripts/commands.sh
RUN ["chmod", "+x", "/scripts/commands.sh"]
ENTRYPOINT ["/scripts/commands.sh"]